// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFY0TTCcdIhIvi25LoEz_tqF0nBfhI5RA',
    appId: '1:419221089542:web:be2eaf2d61fb0286d10287',
    messagingSenderId: '419221089542',
    projectId: 'petremind-b2b41',
    authDomain: 'petremind-b2b41.firebaseapp.com',
    storageBucket: 'petremind-b2b41.firebasestorage.app',
    measurementId: 'G-CY065TVWEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWoLQs24sRPNNV-uKvsjo2um2IF8EZUZA',
    appId: '1:419221089542:android:f6c4f8229e5c581bd10287',
    messagingSenderId: '419221089542',
    projectId: 'petremind-b2b41',
    storageBucket: 'petremind-b2b41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmHlEYovtQvzDl6plvuqqdWa_lSbo8XZs',
    appId: '1:419221089542:ios:ec260c62b04f6bf9d10287',
    messagingSenderId: '419221089542',
    projectId: 'petremind-b2b41',
    storageBucket: 'petremind-b2b41.firebasestorage.app',
    iosBundleId: 'com.example.alarmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmHlEYovtQvzDl6plvuqqdWa_lSbo8XZs',
    appId: '1:419221089542:ios:ec260c62b04f6bf9d10287',
    messagingSenderId: '419221089542',
    projectId: 'petremind-b2b41',
    storageBucket: 'petremind-b2b41.firebasestorage.app',
    iosBundleId: 'com.example.alarmapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFY0TTCcdIhIvi25LoEz_tqF0nBfhI5RA',
    appId: '1:419221089542:web:12efaf77e3af4b46d10287',
    messagingSenderId: '419221089542',
    projectId: 'petremind-b2b41',
    authDomain: 'petremind-b2b41.firebaseapp.com',
    storageBucket: 'petremind-b2b41.firebasestorage.app',
    measurementId: 'G-7JP5R06T7R',
  );
}
